### ISSUE TITLE
table constraints not enforced when using bulk append

### ISSUE THREAD

**Issue by dselivanov** [hannesmuehleisen/MonetDBLite#119] opened 2017-03-19 13:57 UTC
Hi. I'm bit confused with primary keys behaviour - seems they just don't work.
```r
library(DBI)
con = dbConnect(MonetDBLite::MonetDBLite(), tempdir())

df = data.frame(a = 1L, b = 2L)

dbWriteTable(con, "table1", df, append = TRUE)
dbSendQuery(con, "ALTER TABLE table1 ADD CONSTRAINT a_pkey PRIMARY KEY (a)")

dbGetQuery(con, "select count(*) from table1")
# 1

# should violate PK, but inserts successfully
dbWriteTable(con, "table1", df, append = TRUE)

dbGetQuery(con, "select count(*) from table1")
# 2
```

Similar code on RSQLite produce error:
> UNIQUE constraint failed: table1.a

Or I'm just doing something wrong?

> sessionInfo()
R version 3.3.2 (2016-10-31)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: macOS Sierra 10.12.3
locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8
attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     
other attached packages:
[1] MonetDBLite_0.3.2
loaded via a namespace (and not attached):
[1] DBI_0.6          tools_3.3.2      codetools_0.2-15 digest_0.6.12

**Comment by hannesmuehleisen** [comment] 2017-03-20 08:35
confirmed, this looks like a bug to me.

**Comment by dselivanov** [comment] 2017-03-21 06:15
`MonetDB.R` with separate MonetDB installation works fine:
> Server says 'INSERT INTO: PRIMARY KEY constraint 'table1. a_pkey' violated' [#M0M29].

**Comment by hannesmuehleisen** [comment] 2017-03-21 07:42
Yes I'm pretty sure MonetDBLite erroneously commits a transaction it should have aborted. It will be fixed.

**Comment by hannesmuehleisen** [comment] 2017-03-21 09:11
It's the efficient direct table append that goes wrong. An exception is correctly thrown when inserting manually, e.g. `dbSendQuery(con, "insert into table1 values (1, 42)")`

**Comment by hannesmuehleisen** [comment] 2017-03-23 12:45
This needs some serious re-engineering to work correctly.

**Comment by hannesmuehleisen** [comment] 2017-06-15 06:23
we have done the groundwork for this (append running mal plan), should be rel. easy to fix now.

**Comment by hannesmuehleisen** [comment] 2017-06-19 11:13
Fixed in Jul2017 branch.

**Closed by hannesmuehleisen** 2017-06-19 11:13 UTC
