### ISSUE TITLE
Error when connecting to a large table in v0.3.1

### ISSUE THREAD

**Issue by joelgombin** [hannesmuehleisen/MonetDBLite#57] opened 2016-06-20 02:32 UTC
I can't really provide a reprex here, but when linking to a large tbl in a MonetDBLite DB (with something like :

``` r
conn <- src_monetdb(embedded = "~/monetdb")
mytbl <- tbl(conn, from = "mytbl")
```

) RStudio crashes.
When I try the same thing with `MonetBDLite` v0.3.0, it works just fine.

**Comment by ajdamico** [comment] 2016-06-20 03:37
hi joel, first test: try increasing your `memory.limit(64000)`?

if that does not fix it, could you 

1. try the commands using Rterm.exe (not Rgui.exe nor r studio)

2. construct a reproducible example using any of the data sets currently tested by sisyphus?  http://homepages.cwi.nl/~hannes/sisyphus/  (source code https://github.com/MonetDB/eanthony)

thanks!

**Comment by joelgombin** [comment] 2016-06-20 20:27
Hi @ajdamico, thanks for helping me debugging this.
First off, I'm operating under Ubuntu. Sorry, I should have made that clear.
Secondly, when I run the code under R in a terminal, I get:

```r
 *** caught segfault ***
address 0x10, cause 'memory not mapped'

Traceback:
 1: .Call("monetdb_query_R", conn, query, execute, resultconvert,     PACKAGE = libfilename)
 2: monetdb_embedded_query(conn@connenv$conn, statement, execute,     resultconvert)
 3: .local(conn, statement, ...)
 4: dbSendQuery(conn, statement, ...)
 5: dbSendQuery(conn, statement, ...)
 6: DBI::dbGetQuery(con, sql, execute = F)
 7: DBI::dbGetQuery(con, sql, execute = F)
 8: db_query_fields.MonetDBConnection(object$src$con, object$from)
 9: db_query_fields(object$src$con, object$from)
10: update.tbl_sql(tbl)
11: update(tbl)
12: dplyr::tbl_sql("monetdb", src = src, from = from, ...)
13: tbl.src_monetdb(conn, from = "rp_indcvi_2011")
14: tbl(conn, from = "rp_indcvi_2011")
```

I haven't managed yet to make a reprex, I'll keep trying. It is always the same table that seems to make R crash though.

**Comment by ajdamico** [comment] 2016-06-21 01:50
try the dev version

**Comment by ajdamico** [comment] 2016-06-21 07:06
segfaults like these are still being sniffed out and destroyed ;)  you're getting the same error as 

http://homepages.cwi.nl/~hannes/sisyphus/fedora20-4/1466475985/censo.log

on the current run of http://homepages.cwi.nl/~hannes/sisyphus/   so it might not be worth your time coming up with a minimal reproducible example..  but if you do, i can integrate it into our perpetual testing code at https://github.com/MonetDB/eanthony  thanks

**Comment by joelgombin** [comment] 2016-06-21 21:31
It still crashes with the dev version. I'll go back to the 0.3.0 version for now ;-)

**Comment by hannesmuehleisen** [comment] 2016-06-21 22:52
I'd appreciate something I can reproduce here..

**Comment by WesleySilva88** [comment] 2016-07-19 19:30
Hey, @ajdamico,

I've been using your scripts to work with PNAD (link [here](https://github.com/ajdamico/asdfree/blob/master/Pesquisa%20Nacional%20por%20Amostra%20de%20Domicilios/download%20all%20microdata.R)). I have to say: that's a fantastic job! All works fine with the queries in MonetDBLite.

But I also think that it's a good reproducible example about the issue reported here. After I executed all code and created the databese, the exact same error reported by @joelgombin occurs. I tried the following:

`ms <- src_monetdblite(pnad.dbfolder)`
`mt <- tbl(ms,"pnad2014")`

About my System:

`> sessionInfo()
R version 3.2.5 (2016-04-14)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 14.04.4 LTS

locale:
 [1] LC_CTYPE=pt_BR.UTF-8       LC_NUMERIC=C               LC_TIME=pt_BR.UTF-8       
 [4] LC_COLLATE=pt_BR.UTF-8     LC_MONETARY=pt_BR.UTF-8    LC_MESSAGES=pt_BR.UTF-8   
 [7] LC_PAPER=pt_BR.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
[10] LC_TELEPHONE=C             LC_MEASUREMENT=pt_BR.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] tcltk     stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] dplyr_0.5.0.9000  descr_1.1.3       digest_0.6.9      MonetDBLite_0.3.1 DBI_0.4-2        
 [6] SAScii_1.0        stringr_1.0.0     R.utils_2.3.0     R.oo_1.20.0       R.methodsS3_1.7.1
[11] downloader_0.4    RCurl_1.95-4.8    bitops_1.0-6     

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.5      codetools_0.2-14 assertthat_0.1   R6_2.1.2         xtable_1.8-2    
 [6] magrittr_1.5     stringi_1.0-1    rstudioapi_0.5   tools_3.2.5      tibble_1.1 `

**Comment by ajdamico** [comment] 2016-07-20 01:40
hi, @WesleySilva88 i suspect that these crashes are no different from the segfaults on http://homepages.cwi.nl/~hannes/sisyphus/   unrelated to this bug: `dplyr`+survey data only works with `srvyr`

@hannesmuehleisen here's a minimal reproducible example that crashes for me on windows with today's dev MonetDBLite


	# options( encoding = "windows-1252" )		# # only macintosh and *nix users need this line
	library(downloader)
	setwd( "C:/My Directory/PNAD/" )
	years.to.download <- 2014
	# years.to.download <- c( 2001:2009 , 2011:2014 )
	source_url( "https://raw.githubusercontent.com/ajdamico/asdfree/master/Pesquisa%20Nacional%20por%20Amostra%20de%20Domicilios/download%20all%20microdata.R" , prompt = FALSE , echo = FALSE )
	library(dplyr)
	ms <- src_monetdblite(pnad.dbfolder)
	mt <- tbl(ms,"pnad2014")

**Comment by hannesmuehleisen** [comment] 2016-07-21 08:59
ok works fine on OSX ^^

**Comment by ajdamico** [comment] 2016-07-21 09:07
given current sisyphus, not surprising this segfault is windows-only :/

**Comment by hannesmuehleisen** [comment] 2017-01-05 13:24
@joelgombin is this still an issue with the current dev version?

**Comment by ajdamico** [comment] 2017-01-05 13:33
using today's dev version and also dev dplyr, my minimal reproducible example above now works.  my guess is anything else is just a duplicate of the issues in https://github.com/hannesmuehleisen/MonetDBLite/blob/master/tests/testthat/test_05_ram.R  thanks

**Closed** 2017-01-05 15:28 UTC

**Comment by joelgombin** [comment] 2017-01-06 09:25
I confirm this works fine on my end. Thanks!
