### ISSUE TITLE
monetdblite act funny after failed db init

### ISSUE THREAD

**Issue by gijzelaerr** [hannesmuehleisen/MonetDBLite#194] opened 2017-09-06 08:05 UTC
monetdblite refuses to create databases after a failed init.

```
import monetdblite
monetdblite.init('test')
```
gives
```
DatabaseError: Failed to initialize MonetDB: GDKinit() failed. in test
```
If I then try to create a farm  in the same session with a full path:
```
monetdblite.init('/tmp/test')
```
I get:
```
DatabaseError: Failed to initialize MonetDB: !FATAL: BBPaddfarm: bad rolemask
. in /tmp/test
```

**Comment by hannesmuehleisen** [comment] 2017-09-06 09:21
Duplicate of #17

**Closed by hannesmuehleisen** 2017-09-06 09:21 UTC
