### ISSUE TITLE
!FATAL: fixstroffheap: loading string (theap) heap for BAT 16 failed

### ISSUE THREAD

**Issue by joelgombin** [hannesmuehleisen/MonetDBLite#147] opened 2017-05-24 22:40 UTC
When I try to connect to a monetdblite DB, I get this error:

``` r
library(MonetDBLite)
library(DBI)
library(dplyr)
#> 
#> Attachement du package : 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union

con <- dbConnect(monetdblite(), "~/monetdb/")
#> Error in monetdb_embedded_startup(embedded, !getOption("monetdb.debug.embedded", : Failed to initialize embedded MonetDB !FATAL: fixstroffheap: loading string (theap) heap for BAT 16 failed

devtools::session_info()
#> Session info --------------------------------------------------------------
#>  setting  value                       
#>  version  R version 3.4.0 (2017-04-21)
#>  system   x86_64, linux-gnu           
#>  ui       X11                         
#>  language fr_FR                       
#>  collate  fr_FR.UTF-8                 
#>  tz       Europe/Paris                
#>  date     2017-05-25
#> Packages ------------------------------------------------------------------
#>  package     * version    date      
#>  assertthat    0.2.0      2017-04-11
#>  backports     1.0.5      2017-01-18
#>  codetools     0.2-15     2016-10-05
#>  DBI         * 0.6-1      2017-04-01
#>  devtools      1.12.0     2016-12-05
#>  digest        0.6.12     2017-01-27
#>  dplyr       * 0.6.0      2017-05-24
#>  evaluate      0.10       2016-10-11
#>  glue          1.0.0.9000 2017-05-24
#>  htmltools     0.3.6      2017-04-28
#>  knitr         1.15.1     2016-11-22
#>  magrittr      1.5        2014-11-22
#>  memoise       1.1.0      2017-04-21
#>  MonetDBLite * 0.3.2      2017-05-24
#>  R6            2.2.1      2017-05-10
#>  Rcpp          0.12.11    2017-05-22
#>  rlang         0.1.1      2017-05-18
#>  rmarkdown     1.5        2017-04-26
#>  rprojroot     1.2        2017-01-16
#>  stringi       1.1.5      2017-04-07
#>  stringr       1.2.0      2017-02-18
#>  tibble        1.3.1      2017-05-24
#>  withr         1.0.2      2016-06-20
#>  yaml          2.1.14     2016-11-12
#>  source                                       
#>  cran (@0.2.0)                                
#>  CRAN (R 3.3.2)                               
#>  CRAN (R 3.3.1)                               
#>  CRAN (R 3.4.0)                               
#>  CRAN (R 3.4.0)                               
#>  CRAN (R 3.4.0)                               
#>  Github (tidyverse/dplyr@c7ca374)             
#>  CRAN (R 3.3.1)                               
#>  Github (tidyverse/glue@548096b)              
#>  CRAN (R 3.4.0)                               
#>  CRAN (R 3.3.2)                               
#>  CRAN (R 3.4.0)                               
#>  CRAN (R 3.4.0)                               
#>  Github (hannesmuehleisen/MonetDBLite@a82edf7)
#>  cran (@2.2.1)                                
#>  cran (@0.12.11)                              
#>  cran (@0.1.1)                                
#>  cran (@1.5)                                  
#>  CRAN (R 3.3.2)                               
#>  cran (@1.1.5)                                
#>  cran (@1.2.0)                                
#>  Github (tidyverse/tibble@5c183c3)            
#>  CRAN (R 3.4.0)                               
#>  CRAN (R 3.3.2)
```

**Comment by ajdamico** [comment] 2017-05-24 22:58
hi, where is this all-lowercase `monetdblite()` function from?

**Comment by hannesmuehleisen** [comment] 2017-05-25 06:35
@ajdamico, the function is an alias. Overall, this looks like a database corruption. Reasons for this could be disk issues or simply a bug. For the latter, it woud be crucial to create a reproducible example for the issue. Can you provide such an example?

**Comment by ajdamico** [comment] 2017-06-15 14:58
@joelgombin or else please retry with the latest branch, which fixes many bugs related to this error?  thanks

    devtools::install_github( "hannesmuehleisen/MonetDBLite" , ref = "Jul2017Lite-R" )

**Comment by ajdamico** [comment] 2017-07-09 08:04
@joelgombin please retry with master dev branch?  i think this goes to cran soon..thanks

	devtools::install_github( "hannesmuehleisen/MonetDBLite" )

**Comment by hannesmuehleisen** [comment] 2017-08-01 05:37
Any update on this?

**Comment by joelgombin** [comment] 2017-08-01 21:50
Hello,

very sorry for the delay in responding!

I still got the the same output with the last version. I think @hannesmuehleisen is right and the DB is corrupted :/

**Comment by hannes** [comment] 2017-09-14 11:42
Ok sorry for that closing issue here then

**Closed by hannes** 2017-09-14 11:42 UTC
